### ISSUE TITLE
0.1 (beta) Functionality

### ISSUE THREAD

**Issue by radiolevity** [radiolevity/verdant-shores#4]
- [x] Calibration
  - [x] Dec calibration
  - [x] RA calibration (?)
  - [x] Signal calibration
- [x] Data output
  - [x] where do the asterisks go
- [x] Different observation types
  - [x] Scan
  - [x] Survey
  - [x] Spectrum
- [x] make all the different classes in separate files
- [x] either allow different data acquisition rates or make them not editable
- [x] sidereal time calculation
  - [x] when should `sidereal_seconds` equal zero?
- [x] new observation dialog should not have date
- [x] integrate TARS with gui (aka get data to both save and display)
- [x] make `tick()` communicate with both gui AND observation
- [x] add final step of notification system
  - [x] signals for `stop_cal` and `stop_bg`
- [x] debug observation logic

**Comment by radiolevity** [comment]
- [ ] new observation dialog should not have date
- [ ] RA calibration tab order
- [ ] make list of all `#TODO`s in codebase

**Comment by shengjiex98** [comment]
- [ ] Fix T- display so that it's based on time.time() instead of sidereal seconds.
- [ ] Status label should show the state of the program.
- [ ] Fix the problem where declination values in file and in UI are not consistent.

===== After Friday ======
- [ ] Fix UI update frequency.
- [ ] Survey seem to be not beeping enough
- [ ] Bleeps and bloops
